language: go
go:
  - 1.3.3
  - 1.4.2
  - 1.5.1
install:
  - curl -s https://raw.githubusercontent.com/pote/gpm/v1.3.2/bin/gpm > gpm
  - chmod +x gpm
script:
  - ./gpm install
  - ./test.sh
sudo: false
notifications:
  email: false

