version: '2'
services:
  authproxy:
    build: .
    container_name: oauth2-proxy
    image: brunnels/oauth2_proxy
    ports:
      - "80:4180"

  # NGINX example app
  upstream:
      container_name: nginx-test-upstream
      image: nginx
      expose:
          - "80"
